server:
  port: 3000            # The main service port
  useCors: false        # Enable CORS support
rasterizer:
  command: phantomjs    # The phantomjs executable
  port: 3001            # The internal service port
  path: '/tmp/'         # Where screenshot files are stored
  viewport: '1024x600'  # The default browser window size
cache:
  lifetime: 60000       # Cache for 1 minute by default; set to 0 for no caching
